---
- name: Create EC2 instance
  hosts: localhost
  connection: local
  gather_facts: false
  collections:
   - amazon.aws

  vars:
    ansible_python_interpreter: /usr/bin/python3
    region: "ap-south-1"
    instance_type: "t2.micro"
    ami_id: "ami-0376ec8eacdf70aae"
    key_name: "kay-pair"
    security_group: "default"
    subnet_id: "subnet-id"
    instance_name: "ansible-demo-server"
    tag_key: "procenter"
    tag_value: "true"

  tasks:
    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: "{{ instance_name }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        wait: true
        region: "{{ region }}"
        vpc_subnet_id: "{{ subnet_id }}"
        network:
          assign_public_ip: true
        tags: procenter=true
      register: ec2_info

    - name: Display instance ID
      debug:
        var: ec2_info.instances[0].instance_id
 
