---
- name: Stop EC2 instance
  hosts: localhost
  gather_facts: false
  collections:
    - amazon.aws
  vars:
    region: ap-south-1
    instance_id: i-067ac315ce98df4d3
  tasks:
    - name: Stop EC2 instance
      ec2_instance:
        region: "{{ region }}"
        instance_ids: "{{ instance_id }}"
        state: stopped

